"""empty message

Revision ID: 22bf93b3f06f
Revises: abbacb0c48ea
Create Date: 2022-06-07 12:31:14.346035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22bf93b3f06f'
down_revision = 'abbacb0c48ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_products', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_products', 'quantity')
    # ### end Alembic commands ###
