"""empty message

Revision ID: 9c7db2d7ff3f
Revises: 22bf93b3f06f
Create Date: 2022-06-07 12:47:48.343217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c7db2d7ff3f'
down_revision = '22bf93b3f06f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipping_address', sa.String(length=255), nullable=False))
    op.drop_column('users', 'shipping_address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('shipping_address', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('orders', 'shipping_address')
    # ### end Alembic commands ###
