"""empty message

Revision ID: ca8f81adf3cf
Revises: 5a0c2ffa79f7
Create Date: 2022-06-07 10:42:40.480195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca8f81adf3cf'
down_revision = '5a0c2ffa79f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'online')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('online', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
