"""empty message

Revision ID: 5a0c2ffa79f7
Revises: ffdc0a98111c
Create Date: 2022-06-07 10:37:49.525545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a0c2ffa79f7'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('online', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('shipping_address', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'shipping_address')
    op.drop_column('users', 'online')
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###
