"""empty message

Revision ID: 44ca37142b03
Revises: af18ed11ba8c
Create Date: 2022-06-13 20:09:22.090816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44ca37142b03'
down_revision = 'af18ed11ba8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'zipcode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('zipcode', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
