"""empty message

Revision ID: 870a0603e31b
Revises: 17312bb88774
Create Date: 2022-06-13 11:10:05.150447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '870a0603e31b'
down_revision = '17312bb88774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('product_name', sa.String(), nullable=False))
    op.add_column('order_items', sa.Column('product_image', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'product_image')
    op.drop_column('order_items', 'product_name')
    # ### end Alembic commands ###
