"""empty message

Revision ID: af18ed11ba8c
Revises: d6a1ec118166
Create Date: 2022-06-13 19:54:07.285981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af18ed11ba8c'
down_revision = 'd6a1ec118166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('first_name', sa.String(length=255), nullable=False))
    op.add_column('orders', sa.Column('last_name', sa.String(length=255), nullable=False))
    op.add_column('orders', sa.Column('city', sa.String(length=255), nullable=False))
    op.add_column('orders', sa.Column('state', sa.String(length=255), nullable=False))
    op.add_column('orders', sa.Column('zipcode', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'zipcode')
    op.drop_column('orders', 'state')
    op.drop_column('orders', 'city')
    op.drop_column('orders', 'last_name')
    op.drop_column('orders', 'first_name')
    # ### end Alembic commands ###
